name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'master'
env:
  DEFAULT_PYTHON: '3.10'

jobs:
  install_and_collect_jep_artifacts:
    name: Install and collect
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: |
          pip3 install jep
      - name: Cache jep-distro
        uses: actions/cache@v2
        with:
          path: ~/.jep-distro
          key: jep-distro
          enableCrossOsArchive: true
          restore-keys: |
            jep-distro
      - name: Copy jep artifacts on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          mkdir -p ~/.jep-distro/jep
          cp -L ${{ env.pythonLocation }}/lib/python${{ env.DEFAULT_PYTHON }}/site-packages/jep/libjep.so ~/.jep-distro/jep/
          cp ${{ env.pythonLocation }}/lib/python${{ env.DEFAULT_PYTHON }}/site-packages/jep/*.py ~/.jep-distro/jep/
      - name: Copy jep artifacts on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          mkdir -p ~/.jep-distro/jep
          cp ${{ env.pythonLocation }}/lib/python${{ env.DEFAULT_PYTHON }}/site-packages/jep/libjep.jnilib ~/.jep-distro/jep/
      - name: Copy jep artifacts on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          mkdir -p ~/.jep-distro/jep
          ls ${{ env.pythonLocation }}/lib/python${{ env.DEFAULT_PYTHON }}/site-packages/
          cp ${{ env.pythonLocation }}/lib/python${{ env.DEFAULT_PYTHON }}/site-packages/jep/jep.dll ~/.jep-distro/jep/
  archive_and_build:
    name: Archive and build
    runs-on: ${{ matrix.os }}
    needs: install_and_collect_jep_artifacts
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      # actions/checkout v1.* is needed for correct codecov upload, see https://github.com/actions/checkout/issues/237 for details
      - uses: actions/checkout@v1
      # ensure that gradle wrapper files in repository are valid by checking checksums
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache jep-distro
        uses: actions/cache@v2
        with:
          path: ~/.jep-distro
          key: jep-distro
          restore-keys: |
            jep-distro
      - name: Copy jep artifacts on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          tar czvf ~/.jep-distro/jep-distro.tar.gz ~/.jep-distro/jep
